export const roles_pages = {
  Administrador: [
    "/TiposContratos",
    "/TiposDocumentos",
    "/TiposClausulas",
    "/Cargos",
    "/Ejecutivos",
    "/Incoterms",
    "/Puertos",
    "/Monedas",
    "/TiposCompras",
    "/TiposContenedores",
    "/GruposCompra",
    "/FormasPago",
    "/FormasEntrega",
    "/EtapasContratacion",
    "/Usuarios",
    "/BasesGenerales",
    "/BasesGenerales/Add",
    "/BasesGenerales/Edit",
    "/BasesGenerales/Detalle",
    "/CambiarContraseña",
    "/Proformas",
    "/Proformas/Detalle",
    "/ProformasClausulas",
    "/Compradores",
    "/DatosEntidad",
    "/Configuracion",
    "/ContratoMarco",
    "/Negociaciones",
    "/Negociaciones/Add",
    "/Negociaciones/Edit",
    "/Negociaciones/Detalle",
  ],
  ROLE_ENTRENADOR: [
    "/calendario",
    "/clientes",
    "/servicios",
    "/actividades",
    "/cambiarContrasenna",
  ],
  ROLE_CLIENTE: ["/calendario", "/cambiarContrasenna"/* , "/servicios" */],
};
export const unathourized_pages = ["/servicios"];
